---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: prometheus-packages
    kapp.k14s.io/update-strategy: "fallback-on-replace"
  name: prometheus-packages-sa
  namespace: packages
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: prometheus-packages
    kapp.k14s.io/update-strategy: "fallback-on-replace"
  name: prometheus-packages-cluster-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: prometheus-packages
    kapp.k14s.io/update-strategy: "fallback-on-replace"
  name: prometheus-packages-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-packages-cluster-role
subjects:
- kind: ServiceAccount
  name: prometheus-packages-sa
  namespace: packages
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package-ClusterRole: prometheus-packages-cluster-role
    tkg.tanzu.vmware.com/tanzu-package-ClusterRoleBinding: prometheus-packages-cluster-rolebinding
    tkg.tanzu.vmware.com/tanzu-package-Secret: prometheus-packages-values
    tkg.tanzu.vmware.com/tanzu-package-ServiceAccount: prometheus-packages-sa
    ext.packaging.carvel.dev/ytt-paths-from-secret-name.1: alertmanager-overlay
    kapp.k14s.io/update-strategy: "fallback-on-replace"
  name: prometheus
  namespace: packages
spec:
  packageRef:
    refName: prometheus.tanzu.vmware.com
    versionSelection:
      constraints: 2.27.0+vmware.2-tkg.1
  serviceAccountName: prometheus-packages-sa
  values:
  - secretRef:
      name: prometheus-packages-values
