---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: grafana-packages
    kapp.k14s.io/update-strategy: "fallback-on-replace"
  name: grafana-packages-sa
  namespace: packages
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: grafana-packages
    kapp.k14s.io/update-strategy: "fallback-on-replace"
  name: grafana-packages-cluster-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: grafana-packages
    kapp.k14s.io/update-strategy: "fallback-on-replace"
  name: grafana-packages-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: grafana-packages-cluster-role
subjects:
- kind: ServiceAccount
  name: grafana-packages-sa
  namespace: packages
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package-ClusterRole: grafana-packages-cluster-role
    tkg.tanzu.vmware.com/tanzu-package-ClusterRoleBinding: grafana-packages-cluster-rolebinding
    tkg.tanzu.vmware.com/tanzu-package-Secret: grafana-packages-values
    tkg.tanzu.vmware.com/tanzu-package-ServiceAccount: grafana-packages-sa
    kapp.k14s.io/update-strategy: "fallback-on-replace"
  name: grafana
  namespace: packages
spec:
  packageRef:
    refName: grafana.tanzu.vmware.com
    versionSelection:
      constraints: 7.5.16+vmware.1-tkg.1
  serviceAccountName: grafana-packages-sa
  values:
  - secretRef:
      name: grafana-packages-values
