---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: harbor-packages
    kapp.k14s.io/update-strategy: "fallback-on-replace"
  name: harbor-packages-sa
  namespace: packages
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: harbor-packages
    kapp.k14s.io/update-strategy: "fallback-on-replace"
  name: harbor-packages-cluster-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: harbor-packages
    kapp.k14s.io/update-strategy: "fallback-on-replace"
  name: harbor-packages-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: harbor-packages-cluster-role
subjects:
- kind: ServiceAccount
  name: harbor-packages-sa
  namespace: packages
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package-ClusterRole: harbor-packages-cluster-role
    tkg.tanzu.vmware.com/tanzu-package-ClusterRoleBinding: harbor-packages-cluster-rolebinding
    tkg.tanzu.vmware.com/tanzu-package-Secret: harbor-packages-values
    tkg.tanzu.vmware.com/tanzu-package-ServiceAccount: harbor-packages-sa
    kapp.k14s.io/update-strategy: "fallback-on-replace"
  name: harbor
  namespace: packages
spec:
  packageRef:
    refName: harbor.tanzu.vmware.com
    versionSelection:
      constraints: 2.3.3+vmware.1-tkg.1
  serviceAccountName: harbor-packages-sa
  values:
  - secretRef:
      name: harbor-packages-values
