---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: fluent-bit-packages
    kapp.k14s.io/update-strategy: "fallback-on-replace"
  name: fluent-bit-packages-sa
  namespace: packages
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: fluent-bit-packages
    kapp.k14s.io/update-strategy: "fallback-on-replace"
  name: fluent-bit-packages-cluster-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: fluent-bit-packages
    kapp.k14s.io/update-strategy: "fallback-on-replace"
  name: fluent-bit-packages-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluent-bit-packages-cluster-role
subjects:
- kind: ServiceAccount
  name: fluent-bit-packages-sa
  namespace: packages
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package-ClusterRole: fluent-bit-packages-cluster-role
    tkg.tanzu.vmware.com/tanzu-package-ClusterRoleBinding: fluent-bit-packages-cluster-rolebinding
    tkg.tanzu.vmware.com/tanzu-package-Secret: fluent-bit-packages-values
    tkg.tanzu.vmware.com/tanzu-package-ServiceAccount: fluent-bit-packages-sa
    kapp.k14s.io/update-strategy: "fallback-on-replace"
    kapp.k14s.io/create-strategy: "fallback-on-replace"
  name: fluent-bit
  namespace: packages
spec:
  packageRef:
    refName: fluent-bit.tanzu.vmware.com
    versionSelection:
      constraints: 1.7.5+vmware.2-tkg.1
  serviceAccountName: fluent-bit-packages-sa
  values:
  - secretRef:
      name: fluent-bit-packages-values
